swagger: "2.0"
info:
    title: View Collection
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /viewcollection:
        get:
            tags:
                - viewcollection
            summary: list_element viewcollection
            operationId: viewcollection#list_element
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ViewcollectionElementResultResponseTinyCollection'
            schemes:
                - http
    /viewcollection-attr:
        get:
            tags:
                - viewcollection
            summary: list_element_in_attribute viewcollection
            operationId: viewcollection#list_element_in_attribute
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ViewcollectionListElementInAttributeResponseBody'
            schemes:
                - http
definitions:
    ElementResultResponseBody:
        title: 'Mediatype identifier: application/vnd.goaviewcollection.element; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: Creation time of the element
                example: Sit non numquam minus quis sunt.
            description:
                type: string
                description: Description of the element
                example: Quis ad et.
            id:
                type: integer
                description: ID of the element
                example: 6850242382370725814
                format: int64
            name:
                type: string
                description: Name of the element
                example: Voluptatem totam quibusdam.
        description: ElementResultResponseBody result type (default view)
        example:
            created_at: Incidunt recusandae aut consequatur quidem.
            description: Nam illo velit rerum ducimus error.
            id: 3508318184280441581
            name: Officiis omnis.
        required:
            - id
            - name
            - description
            - created_at
    ElementResultResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.goaviewcollection.element; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ElementResultResponseBody'
        description: ElementResultCollectionResponseBody is the result type for an array of ElementResultResponseBody (default view)
        example:
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
    ElementResultResponseTiny:
        title: 'Mediatype identifier: application/vnd.goaviewcollection.element; view=default'
        type: object
        properties:
            id:
                type: integer
                description: ID of the element
                example: 915122920203924960
                format: int64
            name:
                type: string
                description: Name of the element
                example: A eligendi voluptatem reiciendis quis consequuntur mollitia.
        description: ElementResultResponse result type (tiny view) (default view)
        example:
            id: 8575540481389135124
            name: Consequatur voluptatibus quis quaerat vel error in.
        required:
            - id
            - name
    ViewcollectionElementResultResponseTinyCollection:
        title: 'Mediatype identifier: application/vnd.goaviewcollection.element; type=collection; view=tiny'
        type: array
        items:
            $ref: '#/definitions/ElementResultResponseTiny'
        description: ViewcollectionElementResultResponseTinyCollection is the result type for an array of ElementResultResponseTiny (default view)
        example:
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
            - id: 713440558262034984
              name: Et aut sapiente incidunt facere ratione.
    ViewcollectionListElementInAttributeResponseBody:
        title: ViewcollectionListElementInAttributeResponseBody
        type: object
        properties:
            data:
                $ref: '#/definitions/ElementResultResponseBodyCollection'
        example:
            data:
                - created_at: Quo vel alias deleniti voluptatibus sit.
                  description: Tempora est aspernatur ea quia possimus ut.
                  id: 1493121312483939935
                  name: Culpa harum incidunt dolor culpa.
                - created_at: Quo vel alias deleniti voluptatibus sit.
                  description: Tempora est aspernatur ea quia possimus ut.
                  id: 1493121312483939935
                  name: Culpa harum incidunt dolor culpa.
